-- DMC ilk mail açılışı: 5 → 18 spintax varyantı (2026-05-30, Mert onayı)
-- Daha çok varyant = her mail daha farklı = spam parmak izi ↓ (Mert: "spam riskimiz düşer").
-- Yöntem: regexp_replace pipe-içeren {…|…} grubunu hedefler. {{company_name}} (pipe YOK) ve
--   (USD/EUR/GBP) (brace YOK) DOKUNULMAZ. İlk template'te tek pipe-grubu = açılış bloğu.
-- Ton: kibar/resmi, "premium seviyeye taşıyın/farklılaştırın" UKALA laf YOK; özel/ayrıcalıklı/seçkin/premium yat hizmeti çeşitlemesi.

BEGIN;

-- body_text (bare {…})
UPDATE email_templates SET body_text = regexp_replace(body_text,
  '\{[^{}]*\|[^{}]*\}',
  $Q${İstanbul'a ağırladığınız grupların tur programlarına Boğaz'da özel bir yat deneyimi eklemek üzere sizinle iletişime geçiyoruz.|Misafirlerinize sunduğunuz İstanbul tur programlarına Boğaz'da özel bir yat deneyimi katma fikriyle yazıyoruz.|İstanbul tur programlarınıza Boğaz'da ayrıcalıklı bir yat deneyimi eklemenin yollarını paylaşmak isteriz.|Ağırladığınız grupların İstanbul programlarına Boğaz'da premium bir yat hizmeti eklemek üzere bir önerimizi paylaşmak isteriz.|Misafir gruplarınızın İstanbul tur programlarına Boğaz'da özel bir yat deneyimi katmayı sizinle değerlendirmek isteriz.|İstanbul'a getirdiğiniz misafir gruplarına Boğaz'da özel bir yat günü sunma fikrini sizinle paylaşmak istedik.|Klasik İstanbul tur programlarınızı Boğaz'da seçkin bir yat deneyimiyle tamamlamak için bir önerimiz var.|Misafirlerinize İstanbul turlarının yanı sıra Boğaz'da özel bir yat deneyimi sunma olanağını konuşmak isteriz.|İstanbul programlarınıza Boğaz'da ayrıcalıklı bir yat seçeneği eklemek konusunda sizinle görüşmek isteriz.|Ağırladığınız gruplara Boğaz'da özel bir yat deneyimi sunma imkânını değerlendirmek üzere yazıyoruz.|İstanbul'da misafir ettiğiniz gruplara Boğaz'da seçkin bir yat hizmeti sunmak için sizinle tanışmak isteriz.|Tur programlarınıza Boğaz'da özel bir yat deneyimi eklemenin sizin için nasıl işleyebileceğini paylaşmak isteriz.|İstanbul'a ağırladığınız misafirlere Boğaz'da ayrıcalıklı bir yat günü sunma önerimizi iletmek isteriz.|Misafir gruplarınızın İstanbul deneyimine Boğaz'da özel bir yat dokunuşu eklemek için yazıyoruz.|İstanbul tur programlarınızda Boğaz'da premium bir yat hizmetine yer açmanın yollarını konuşmak isteriz.|Ağırladığınız uluslararası gruplara Boğaz'da seçkin bir yat deneyimi sunma fikrini paylaşmak istedik.|İstanbul'da misafir ettiğiniz gruplara Boğaz'da özel bir yat programı sunma olanağını değerlendirmek isteriz.|Klasik İstanbul turlarınıza Boğaz'da ayrıcalıklı bir yat deneyimi eklemek üzere sizinle iletişimdeyiz.}$Q$,
  'g')
WHERE name = 'outreach_initial_agency_dmc_tr';

-- body_html (aynı blok; <p> sarmalı korunur, sadece {…} değişir)
UPDATE email_templates SET body_html = regexp_replace(body_html,
  '\{[^{}]*\|[^{}]*\}',
  $Q${İstanbul'a ağırladığınız grupların tur programlarına Boğaz'da özel bir yat deneyimi eklemek üzere sizinle iletişime geçiyoruz.|Misafirlerinize sunduğunuz İstanbul tur programlarına Boğaz'da özel bir yat deneyimi katma fikriyle yazıyoruz.|İstanbul tur programlarınıza Boğaz'da ayrıcalıklı bir yat deneyimi eklemenin yollarını paylaşmak isteriz.|Ağırladığınız grupların İstanbul programlarına Boğaz'da premium bir yat hizmeti eklemek üzere bir önerimizi paylaşmak isteriz.|Misafir gruplarınızın İstanbul tur programlarına Boğaz'da özel bir yat deneyimi katmayı sizinle değerlendirmek isteriz.|İstanbul'a getirdiğiniz misafir gruplarına Boğaz'da özel bir yat günü sunma fikrini sizinle paylaşmak istedik.|Klasik İstanbul tur programlarınızı Boğaz'da seçkin bir yat deneyimiyle tamamlamak için bir önerimiz var.|Misafirlerinize İstanbul turlarının yanı sıra Boğaz'da özel bir yat deneyimi sunma olanağını konuşmak isteriz.|İstanbul programlarınıza Boğaz'da ayrıcalıklı bir yat seçeneği eklemek konusunda sizinle görüşmek isteriz.|Ağırladığınız gruplara Boğaz'da özel bir yat deneyimi sunma imkânını değerlendirmek üzere yazıyoruz.|İstanbul'da misafir ettiğiniz gruplara Boğaz'da seçkin bir yat hizmeti sunmak için sizinle tanışmak isteriz.|Tur programlarınıza Boğaz'da özel bir yat deneyimi eklemenin sizin için nasıl işleyebileceğini paylaşmak isteriz.|İstanbul'a ağırladığınız misafirlere Boğaz'da ayrıcalıklı bir yat günü sunma önerimizi iletmek isteriz.|Misafir gruplarınızın İstanbul deneyimine Boğaz'da özel bir yat dokunuşu eklemek için yazıyoruz.|İstanbul tur programlarınızda Boğaz'da premium bir yat hizmetine yer açmanın yollarını konuşmak isteriz.|Ağırladığınız uluslararası gruplara Boğaz'da seçkin bir yat deneyimi sunma fikrini paylaşmak istedik.|İstanbul'da misafir ettiğiniz gruplara Boğaz'da özel bir yat programı sunma olanağını değerlendirmek isteriz.|Klasik İstanbul turlarınıza Boğaz'da ayrıcalıklı bir yat deneyimi eklemek üzere sizinle iletişimdeyiz.}$Q$,
  'g')
WHERE name = 'outreach_initial_agency_dmc_tr';

COMMIT;
